import { Product } from './types';

export const CATEGORIES = ['All', 'Sofas', 'Beds', 'Chairs', 'Tables', 'Wardrobes', 'Decor'];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Royal Maharaja Sofa Set',
    category: 'Sofas',
    price: 65000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&q=80&w=800',
    description: 'Experience royalty with this handcrafted Chesterfield sofa set in premium teal velvet. Perfect for a luxurious living room in Bhopal.',
    materials: ['Premium Velvet', 'Teak Wood Frame', 'Gold Leaf Detailing'],
    dimensions: '3 Seater + 2 Single Seaters',
    inStock: true,
  },
  {
    id: '2',
    name: 'Modern King Size Bed',
    category: 'Beds',
    price: 42000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?auto=format&fit=crop&q=80&w=800',
    description: 'Sleek and sturdy king-size bed with hydraulic storage. Designed for modern Indian homes with a minimalist aesthetic.',
    materials: ['Engineered Wood', 'Matte Finish Laminate', 'Hydraulic Lift'],
    dimensions: '72 x 78 inches (King)',
    inStock: true,
  },
  {
    id: '3',
    name: 'Sheesham Wood Dining',
    category: 'Tables',
    price: 38000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1577140917170-285929fb55b7?auto=format&fit=crop&q=80&w=800',
    description: 'A 6-seater solid Sheesham wood dining table set with cushioned chairs. Durable, elegant, and perfect for family dinners.',
    materials: ['Solid Sheesham Wood', 'Honey Finish', 'Fabric Cushions'],
    dimensions: '6 Seater Table',
    inStock: true,
  },
  {
    id: '4',
    name: 'Luxury Recliner Chair',
    category: 'Chairs',
    price: 22500,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&q=80&w=800',
    description: 'Ultra-comfortable single seater recliner upholstered in breathable fabric. Your perfect companion for reading or relaxing.',
    materials: ['High-Density Foam', 'Imported Fabric', 'Steel Mechanism'],
    dimensions: 'Standard Recliner Size',
    inStock: true,
  },
  {
    id: '5',
    name: '4-Door Designer Wardrobe',
    category: 'Wardrobes',
    price: 55000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&q=80&w=800',
    description: 'Spacious 4-door wardrobe with full-length mirror and ample storage compartments. Elegant wood finish.',
    materials: ['Ply & Laminate', 'Soft Close Hinges'],
    dimensions: '6ft x 7ft',
    inStock: true,
  },
  {
    id: '6',
    name: 'Marble Top Coffee Table',
    category: 'Tables',
    price: 18000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?auto=format&fit=crop&q=80&w=800',
    description: 'Italian marble top center table with a gold-finished geometric metal base. A centerpiece for your lounge.',
    materials: ['Italian Marble', 'SS Gold PVD Coating'],
    dimensions: '3ft Diameter',
    inStock: true,
  },
  {
    id: '7',
    name: 'L-Shape Sectional Sofa',
    category: 'Sofas',
    price: 48000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    description: 'Modern L-shaped sofa with adjustable headrests. Maximize seating in your living room without compromising on style.',
    materials: ['Suede Fabric', 'Solid Wood Structure'],
    dimensions: '8ft x 6ft',
    inStock: true,
  },
  {
    id: '8',
    name: 'Antique Wall Mirror',
    category: 'Decor',
    price: 6500,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1622372738946-62e02505feb3?auto=format&fit=crop&q=80&w=800',
    description: 'Hand-carved wooden frame mirror with an antique gold finish. Adds depth and beauty to any wall.',
    materials: ['Mango Wood', 'Glass', 'Gold Paint'],
    dimensions: '24 x 36 inches',
    inStock: true,
  },
  {
    id: '9',
    name: 'Ergonomic Office Chair',
    category: 'Chairs',
    price: 12500,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&q=80&w=800',
    description: 'High-back mesh office chair with lumbar support and adjustable height. Perfect for work-from-home setups.',
    materials: ['Mesh Back', 'Nylon Base', 'Moulded Foam'],
    dimensions: 'Adjustable Height',
    inStock: true,
  },
  {
    id: '10',
    name: 'Teak Wood Console',
    category: 'Decor',
    price: 15000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800',
    description: 'Slim console table for entryways or hallways. Crafted from genuine teak wood.',
    materials: ['Teak Wood', 'Natural Polish'],
    dimensions: '4ft x 12 inches',
    inStock: false,
  }
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priya Sharma',
    text: 'Akash Interio transformed my living room in Arera Colony. The Sofa set is royal and very comfortable.',
    role: 'Homeowner',
  },
  {
    id: 2,
    name: 'Rajesh Gupta',
    text: 'Best furniture shop in Kolar Road. I bought a bed and dining table, the quality is top-notch.',
    role: 'Businessman',
  },
  {
    id: 3,
    name: 'Amit Verma',
    text: 'Excellent service and genuine pricing. The custom wardrobe they made fits perfectly in my room.',
    role: 'Architect',
  }
];